(load "interpret.scm")

(string-append "test 1: " (if (eq? (interpret "tests/Test2-01.txt" ) 20) "passed" "failed"))
(string-append "test 2: " (if (eq? (interpret "tests/Test2-02.txt" ) 164) "passed" "failed")) 
(string-append "test 3: " (if (eq? (interpret "tests/Test2-03.txt" ) 32) "passed" "failed"))
(string-append "test 4: " (if (eq? (interpret "tests/Test2-04.txt" ) 2) "passed" "failed")) 
;(string-append "test 5: " (if (equal? (interpret "tests/Test2-05.txt" ) (error)) "passed" "failed"))
(string-append "test 6: " (if (eq? (interpret "tests/Test2-06.txt" ) 25) "passed" "failed"))
(string-append "test 7: " (if (eq? (interpret "tests/Test2-07.txt" ) 21) "passed" "failed"))
(string-append "test 8: " (if (eq? (interpret "tests/Test2-08.txt" ) 6) "passed" "failed"))
(string-append "test 9: " (if (eq? (interpret "tests/Test2-09.txt" ) -1) "passed" "failed"))
(string-append "test 10: " (if (eq? (interpret "tests/Test2-10.txt" ) 789) "passed" "failed"))
;(string-append "test 11: " (if (eq? (interpret "tests/Test2-11.txt" ) (error)) "passed" "failed"))
;(string-append "test 12: " (if (eq? (interpret "tests/Test2-12.txt" ) (error)) "passed" "failed"))
;(string-append "test 13: " (if (eq? (interpret "tests/Test2-13.txt" ) (error)) "passed" "failed"))
(string-append "test 14: " (if (eq? (interpret "tests/Test2-14.txt" ) 12) "passed" "failed"))
(string-append "test 15: " (if (eq? (interpret "tests/Test2-15.txt" ) 125) "passed" "failed"))
(string-append "test 16: " (if (eq? (interpret "tests/Test2-16.txt" ) 110) "passed" "failed"))
(string-append "test 17: " (if (eq? (interpret "tests/Test2-17.txt" ) 2000400) "passed" "failed")) 
(string-append "test 18: " (if (eq? (interpret "tests/Test2-18.txt" ) 101) "passed" "failed")) 
;(string-append "test 19: " (if (eq? (interpret "tests/Test2-19.txt" ) (error)) "passed" "failed")) 
; bonus
(string-append "test 20: " (if (eq? (interpret "tests/Test2-20.txt" ) 21) "passed" "failed")) 